name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY_NAME: naveencst

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform -chdir=infra init -reconfigure

    - name: Terraform Apply
      run: terraform -chdir=infra apply -auto-approve

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get ECR Repository URI
      id: get-ecr-uri
      run: |
        URI=$(aws ecr describe-repositories \
          --repository-names ${{ env.ECR_REPOSITORY_NAME }} \
          --region ${{ env.AWS_REGION }} \
          --query 'repositories[0].repositoryUri' --output text)
        echo "URI=$URI" >> $GITHUB_ENV

    - name: Build and Push Docker Image to ECR
      run: |
        docker build -t $URI:latest ./app
        docker push $URI:latest

    - name: Update ECS Service
      run: |
        aws ecs update-service \
          --cluster naveencst \
          --service naveencst \
          --force-new-deployment \
          --region ${{ env.AWS_REGION }}

