name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    # Ensure ECR force_delete is applied
    - name: Destroy ECR Repository
      #run: terraform apply -target=module.ecr -auto-approve
      run: terraform destroy -target=module.ecr.aws_ecr_repository.foo -auto-approve

    # Destroy ECS service first
    - name: Destroy ECS Service
      run: terraform destroy -target=module.ecs.aws_ecs_service.naveen-service -auto-approve

    # Then destroy everything else
    - name: Destroy All Infrastructure
      run: terraform destroy -auto-approve
